### ISSUE TITLE
Hi, this error every times show me. Any help? Uncaught (in promise) FirebaseError: Missing or insufficient permissions.

### ISSUE THREAD

**Issue by ukicomputers** [iamshaunjp/firebase-firestore-playlist#13]
![Screenshot (6)](https://user-images.githubusercontent.com/84191191/182626815-fd629a37-b518-48c5-8565-24073c68b361.png)
Uncaught (in promise) FirebaseError: Missing or insufficient permissions.

**Comment by reed-codes** [comment]
This looks like it's from net ninja's old firebase tutorial - firebase has changed quite a bit since then so I'd recommend you find a different and more up-to-date tutorial on Firebase

**Comment by ukicomputers** [comment]
Thanks, I find! To help people, I here will share code for newer Firebase versions:

<!DOCTYPE html>
<html>
    <head>
        <script src="https://www.gstatic.com/firebasejs/8.10.1/firebase-app.js"></script>
        <script src="https://www.gstatic.com/firebasejs/8.10.1/firebase-firestore.js"></script>
    </head>
</html>

<script type="module">
    import { initializeApp } from "https://www.gstatic.com/firebasejs/9.4.0/firebase-app.js";
    import { getFirestore, doc, getDoc, getDocs, collection, query, where } from "https://www.gstatic.com/firebasejs/9.4.0/firebase-firestore.js";
    const firebaseConfig = {
        //put here your firebase informations
    };
    const app = initializeApp(firebaseConfig);
    const db = getFirestore(app);

    //test reading from console
    const q = query(collection(db, "casopisi"));
    const querySnapshot = await getDocs(q);
    querySnapshot.forEach((doc) => {
        console.log(doc.id, " => ", doc.data());
    });
</script>
